from gi.repository import Gtk
# instantiate XML object
gui = Gtk.Builder()
gui.add_from_file("communicator.glade")
# get references to individual widgets

class communicator:
   def __init__(self):
        hbsCommunicatorWindow = gui.get_object("hbsCommunicator")
        hbsCommunicatorWindow.show_all()
        comWindow = gui.get_object("comWindow")
        navBox = gui.get_object("navBox")
        channelLabel = gui.get_object("channelLabel")
        channelNotebook = gui.get_object("channelNotebook")
        commandNavBox = gui.get_object("commandNavBox")
        centralCommandButton = gui.get_object("centralCommandButton")
        operationsCommandButton = gui.get_object("operationsCommandButton")
        codCommandButton = gui.get_object("codCommandButton")
        rustCommandButton = gui.get_object("rustCommandButton")
        gwCommandButton = gui.get_object("gwCommandButton")
        wowCommandButton = gui.get_object("wowCommandButton")
        mcCommandButton = gui.get_object("mcCommandButton")
        armaCommandButton = gui.get_object("armaCommandButton")
        logisticsCommandButton = gui.get_object("logisticsCommandButton")
        mpCommandButton = gui.get_object("mpCommandButton")
        admissionsCommandButton = gui.get_object("admissionsCommandButton")
        commandTab = gui.get_object("commandTab")
        generalNavBox = gui.get_object("generalNavBox")
        generalButton = gui.get_object("generalButton")
        codGeneralButton = gui.get_object("ccodGeneralButton")
        rustGeneralButton = gui.get_object("rustGeneralButton")
        gwGeneralButton = gui.get_object("gwGeneralButton")
        wowGeneralButton = gui.get_object("wowGeneralButton")
        mcGeneralButton = gui.get_object("mcGeneralButton")
        armaGeneralButton = gui.get_object("armaGeneralButton")
        generalTab = gui.get_object("generalTab")
        contentGrid = gui.get_object("contentGrid")
        submitGrid = gui.get_object("submitGrid")
        chatEntry = gui.get_object("chatEntry")
        submitButton = gui.get_object("submitButton")
        contentNotebook = gui.get_object("contentNotebook")
        infoDisplay = gui.get_object("infoDisplay")
        channelTab = gui.get_object("channelTab")
        rosterTextView = gui.get_object("rosterTextView")
        rosterTab = gui.get_object("rosterTab")


app = communicator()
Gtk.main()
