# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_communicator.ui'
#
# Created: Wed May 14 19:35:53 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_hbsCommunicator(object):
    def setupUi(self, hbsCommunicator):
        hbsCommunicator.setObjectName(_fromUtf8("hbsCommunicator"))
        hbsCommunicator.setEnabled(True)
        hbsCommunicator.resize(982, 639)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(hbsCommunicator.sizePolicy().hasHeightForWidth())
        hbsCommunicator.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(hbsCommunicator)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_8 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.userButton = QtGui.QPushButton(self.centralwidget)
        self.userButton.setEnabled(False)
        self.userButton.setMinimumSize(QtCore.QSize(138, 28))
        self.userButton.setText(_fromUtf8(""))
        self.userButton.setFlat(True)
        self.userButton.setObjectName(_fromUtf8("userButton"))
        self.gridLayout_8.addWidget(self.userButton, 0, 0, 1, 1)
        self.channelNotebook = QtGui.QTabWidget(self.centralwidget)
        self.channelNotebook.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.channelNotebook.sizePolicy().hasHeightForWidth())
        self.channelNotebook.setSizePolicy(sizePolicy)
        self.channelNotebook.setMinimumSize(QtCore.QSize(0, 0))
        self.channelNotebook.setMaximumSize(QtCore.QSize(215, 16777215))
        self.channelNotebook.setTabPosition(QtGui.QTabWidget.North)
        self.channelNotebook.setTabShape(QtGui.QTabWidget.Rounded)
        self.channelNotebook.setElideMode(QtCore.Qt.ElideNone)
        self.channelNotebook.setTabsClosable(False)
        self.channelNotebook.setMovable(False)
        self.channelNotebook.setObjectName(_fromUtf8("channelNotebook"))
        self.commandTab = QtGui.QWidget()
        self.commandTab.setObjectName(_fromUtf8("commandTab"))
        self.gridLayout = QtGui.QGridLayout(self.commandTab)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.commandLayout = QtGui.QVBoxLayout()
        self.commandLayout.setSpacing(0)
        self.commandLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.commandLayout.setContentsMargins(0, -1, -1, -1)
        self.commandLayout.setObjectName(_fromUtf8("commandLayout"))
        self.gridLayout.addLayout(self.commandLayout, 0, 0, 1, 1)
        self.channelNotebook.addTab(self.commandTab, _fromUtf8(""))
        self.generalTab = QtGui.QWidget()
        self.generalTab.setObjectName(_fromUtf8("generalTab"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.generalTab)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.generalLayout = QtGui.QVBoxLayout()
        self.generalLayout.setObjectName(_fromUtf8("generalLayout"))
        self.verticalLayout_6.addLayout(self.generalLayout)
        self.channelNotebook.addTab(self.generalTab, _fromUtf8(""))
        self.gridLayout_8.addWidget(self.channelNotebook, 1, 0, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.contentNotebook = QtGui.QTabWidget(self.centralwidget)
        self.contentNotebook.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.contentNotebook.sizePolicy().hasHeightForWidth())
        self.contentNotebook.setSizePolicy(sizePolicy)
        self.contentNotebook.setTabsClosable(False)
        self.contentNotebook.setObjectName(_fromUtf8("contentNotebook"))
        self.channelTab = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.channelTab.sizePolicy().hasHeightForWidth())
        self.channelTab.setSizePolicy(sizePolicy)
        self.channelTab.setObjectName(_fromUtf8("channelTab"))
        self.gridLayout_4 = QtGui.QGridLayout(self.channelTab)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.channelDisplay = QtGui.QPlainTextEdit(self.channelTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.channelDisplay.sizePolicy().hasHeightForWidth())
        self.channelDisplay.setSizePolicy(sizePolicy)
        self.channelDisplay.setAcceptDrops(False)
        self.channelDisplay.setAutoFillBackground(False)
        self.channelDisplay.setFrameShape(QtGui.QFrame.NoFrame)
        self.channelDisplay.setFrameShadow(QtGui.QFrame.Plain)
        self.channelDisplay.setReadOnly(True)
        self.channelDisplay.setCenterOnScroll(False)
        self.channelDisplay.setObjectName(_fromUtf8("channelDisplay"))
        self.gridLayout_4.addWidget(self.channelDisplay, 0, 1, 1, 1)
        self.loginGroupBox = QtGui.QGroupBox(self.channelTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loginGroupBox.sizePolicy().hasHeightForWidth())
        self.loginGroupBox.setSizePolicy(sizePolicy)
        self.loginGroupBox.setFlat(True)
        self.loginGroupBox.setObjectName(_fromUtf8("loginGroupBox"))
        self.gridGroupBox = QtGui.QGroupBox(self.loginGroupBox)
        self.gridGroupBox.setEnabled(True)
        self.gridGroupBox.setGeometry(QtCore.QRect(70, 0, 461, 261))
        self.gridGroupBox.setAutoFillBackground(False)
        self.gridGroupBox.setFlat(True)
        self.gridGroupBox.setObjectName(_fromUtf8("gridGroupBox"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gridGroupBox)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.passwordLabel = QtGui.QLabel(self.gridGroupBox)
        self.passwordLabel.setObjectName(_fromUtf8("passwordLabel"))
        self.gridLayout_2.addWidget(self.passwordLabel, 1, 0, 1, 1)
        self.usernameEntry = QtGui.QLineEdit(self.gridGroupBox)
        self.usernameEntry.setEnabled(True)
        self.usernameEntry.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.usernameEntry.setObjectName(_fromUtf8("usernameEntry"))
        self.gridLayout_2.addWidget(self.usernameEntry, 0, 1, 1, 1)
        self.passwordEntry = QtGui.QLineEdit(self.gridGroupBox)
        self.passwordEntry.setEnabled(True)
        self.passwordEntry.setEchoMode(QtGui.QLineEdit.Password)
        self.passwordEntry.setObjectName(_fromUtf8("passwordEntry"))
        self.gridLayout_2.addWidget(self.passwordEntry, 1, 1, 1, 1)
        self.usernameLabel = QtGui.QLabel(self.gridGroupBox)
        self.usernameLabel.setObjectName(_fromUtf8("usernameLabel"))
        self.gridLayout_2.addWidget(self.usernameLabel, 0, 0, 1, 1)
        self.loginButton = QtGui.QPushButton(self.loginGroupBox)
        self.loginButton.setGeometry(QtCore.QRect(310, 295, 211, 31))
        self.loginButton.setAutoDefault(False)
        self.loginButton.setObjectName(_fromUtf8("loginButton"))
        self.loginStatusLabel = QtGui.QLabel(self.loginGroupBox)
        self.loginStatusLabel.setGeometry(QtCore.QRect(40, 295, 261, 31))
        self.loginStatusLabel.setObjectName(_fromUtf8("loginStatusLabel"))
        self.rememberLoginCheck = QtGui.QCheckBox(self.loginGroupBox)
        self.rememberLoginCheck.setEnabled(True)
        self.rememberLoginCheck.setGeometry(QtCore.QRect(373, 340, 141, 26))
        self.rememberLoginCheck.setObjectName(_fromUtf8("rememberLoginCheck"))
        self.gridLayout_4.addWidget(self.loginGroupBox, 0, 0, 1, 1)
        self.contentNotebook.addTab(self.channelTab, _fromUtf8(""))
        self.rosterTab = QtGui.QWidget()
        self.rosterTab.setObjectName(_fromUtf8("rosterTab"))
        self.gridLayout_6 = QtGui.QGridLayout(self.rosterTab)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.rosterDisplay = QtGui.QPlainTextEdit(self.rosterTab)
        self.rosterDisplay.setFrameShape(QtGui.QFrame.NoFrame)
        self.rosterDisplay.setFrameShadow(QtGui.QFrame.Plain)
        self.rosterDisplay.setReadOnly(True)
        self.rosterDisplay.setObjectName(_fromUtf8("rosterDisplay"))
        self.gridLayout_6.addWidget(self.rosterDisplay, 0, 0, 1, 1)
        self.gridLayoutWidget = QtGui.QWidget(self.rosterTab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(270, 160, 160, 80))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout_5 = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_5.setMargin(0)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.contentNotebook.addTab(self.rosterTab, _fromUtf8(""))
        self.gridLayout_3.addWidget(self.contentNotebook, 0, 0, 1, 1)
        self.widget = QtGui.QWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(150, 0))
        self.widget.setMaximumSize(QtCore.QSize(150, 16777215))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout_7 = QtGui.QGridLayout(self.widget)
        self.gridLayout_7.setMargin(0)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.onlineLabel = QtGui.QLabel(self.widget)
        self.onlineLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.onlineLabel.setObjectName(_fromUtf8("onlineLabel"))
        self.gridLayout_7.addWidget(self.onlineLabel, 0, 0, 1, 1)
        self.onlineList = QtGui.QPlainTextEdit(self.widget)
        self.onlineList.setAcceptDrops(False)
        self.onlineList.setAutoFillBackground(False)
        self.onlineList.setFrameShape(QtGui.QFrame.NoFrame)
        self.onlineList.setFrameShadow(QtGui.QFrame.Sunken)
        self.onlineList.setReadOnly(True)
        self.onlineList.setBackgroundVisible(False)
        self.onlineList.setObjectName(_fromUtf8("onlineList"))
        self.gridLayout_7.addWidget(self.onlineList, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.widget, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.gridLayout_8.addLayout(self.verticalLayout, 1, 1, 1, 1)
        self.refreshButton = QtGui.QPushButton(self.centralwidget)
        self.refreshButton.setMaximumSize(QtCore.QSize(0, 0))
        self.refreshButton.setObjectName(_fromUtf8("refreshButton"))
        self.gridLayout_8.addWidget(self.refreshButton, 2, 0, 1, 1)
        self.submitLayout = QtGui.QHBoxLayout()
        self.submitLayout.setObjectName(_fromUtf8("submitLayout"))
        self.chatEntry = QtGui.QLineEdit(self.centralwidget)
        self.chatEntry.setEnabled(False)
        self.chatEntry.setAutoFillBackground(True)
        self.chatEntry.setObjectName(_fromUtf8("chatEntry"))
        self.submitLayout.addWidget(self.chatEntry)
        self.submitButton = QtGui.QPushButton(self.centralwidget)
        self.submitButton.setEnabled(False)
        self.submitButton.setObjectName(_fromUtf8("submitButton"))
        self.submitLayout.addWidget(self.submitButton)
        self.gridLayout_8.addLayout(self.submitLayout, 2, 1, 1, 1)
        self.announcementLabel = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.announcementLabel.sizePolicy().hasHeightForWidth())
        self.announcementLabel.setSizePolicy(sizePolicy)
        self.announcementLabel.setAutoFillBackground(False)
        self.announcementLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.announcementLabel.setIndent(0)
        self.announcementLabel.setOpenExternalLinks(True)
        self.announcementLabel.setObjectName(_fromUtf8("announcementLabel"))
        self.gridLayout_8.addWidget(self.announcementLabel, 3, 0, 1, 2)
        hbsCommunicator.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(hbsCommunicator)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 982, 27))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        hbsCommunicator.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(hbsCommunicator)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        hbsCommunicator.setStatusBar(self.statusbar)

        self.retranslateUi(hbsCommunicator)
        self.channelNotebook.setCurrentIndex(0)
        self.contentNotebook.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(hbsCommunicator)
        hbsCommunicator.setTabOrder(self.usernameEntry, self.passwordEntry)
        hbsCommunicator.setTabOrder(self.passwordEntry, self.loginButton)
        hbsCommunicator.setTabOrder(self.loginButton, self.channelNotebook)
        hbsCommunicator.setTabOrder(self.channelNotebook, self.chatEntry)
        hbsCommunicator.setTabOrder(self.chatEntry, self.submitButton)
        hbsCommunicator.setTabOrder(self.submitButton, self.refreshButton)
        hbsCommunicator.setTabOrder(self.refreshButton, self.rosterDisplay)
        hbsCommunicator.setTabOrder(self.rosterDisplay, self.userButton)

    def retranslateUi(self, hbsCommunicator):
        hbsCommunicator.setWindowTitle(_translate("hbsCommunicator", "HBS Communicator", None))
        self.channelNotebook.setTabText(self.channelNotebook.indexOf(self.commandTab), _translate("hbsCommunicator", "Command", None))
        self.channelNotebook.setTabText(self.channelNotebook.indexOf(self.generalTab), _translate("hbsCommunicator", "General", None))
        self.passwordLabel.setText(_translate("hbsCommunicator", "Password:", None))
        self.usernameLabel.setText(_translate("hbsCommunicator", "Username:", None))
        self.loginButton.setText(_translate("hbsCommunicator", "Login", None))
        self.loginStatusLabel.setText(_translate("hbsCommunicator", "Hint: Same as forum", None))
        self.rememberLoginCheck.setText(_translate("hbsCommunicator", "Remember Login", None))
        self.contentNotebook.setTabText(self.contentNotebook.indexOf(self.channelTab), _translate("hbsCommunicator", "Channel", None))
        self.contentNotebook.setTabText(self.contentNotebook.indexOf(self.rosterTab), _translate("hbsCommunicator", "Roster", None))
        self.onlineLabel.setText(_translate("hbsCommunicator", "Online", None))
        self.refreshButton.setText(_translate("hbsCommunicator", "Refresh", None))
        self.submitButton.setText(_translate("hbsCommunicator", "Submit", None))
        self.announcementLabel.setText(_translate("hbsCommunicator", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Cantarell\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">HBS Communicator Version 0.10.0 - Beta</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Please report all bugs and features <a href=\"http://hellboundsoldiers.org/forums/forumdisplay.php?150-HBS-COMMUNICATOR\"><span style=\" text-decoration: underline; color:#0000ff;\">here</span></a></p></body></html>", None))

